# Generated by Django 6.0.7 on 2026-08-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='business_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason_for_booking',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
