# Generated by Django 6.0.7 on 2026-08-26 08:35

from django.db import migrations, models


def migrate_active_to_completed(apps, schema_editor):
    BusinessRegistration = apps.get_model('main_app', 'BusinessRegistration')
    BusinessRegistration.objects.filter(status='active').update(status='completed')


def reverse_completed_to_active(apps, schema_editor):
    BusinessRegistration = apps.get_model('main_app', 'BusinessRegistration')
    BusinessRegistration.objects.filter(status='completed').update(status='active')


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_booking_business_type_booking_reason_for_booking_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_active_to_completed, reverse_completed_to_active),
        migrations.AlterField(
            model_name='businessregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved for CR Support'), ('in_progress', 'CR Support in Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
